name: Build using artefacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}


