name: Build using artefacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build and Deploy to GitHub
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: Setup - Maven settings
        uses: s4u/maven-settings-action@64e42c454dbd42ef6370ac8539685755aedd205b # v3.1.0
        with:
          githubServer: false
          servers: >-
            [
              {
                  "id": "repsy",
                  "username": "${{ secrets.REPSY_USER }}",
                  "password": "${{ secrets.REPSY_PASSWORD }}"
              }
            ]

      - name: Deploy to Repsy
        run:  mvn deploy:deploy-file -Prepsy-deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}



